// <auto-generated />
using Bulky.DataAccess.DATA; 
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky_Web_MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231117103615_SeedCategoryTable")]
    partial class SeedCategoryTable : SeedCategoryTableBase
    {
    }
}
